# Server Configuration
server:
  port: 8083

# PostgreSQL Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rating_service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver