# Server Configuration
server:
  port: 8081

# Spring Configuration
spring:
  application:
    name: USER-SERVICE

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
